server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        # Em produção, se o front e a API estiverem no mesmo domínio, use proxy_pass para a API
        # proxy_pass http://sua-api:3000;
        return 404;
    }
}
